### ISSUE TITLE
How do I load the fine tuned model for inference?

### ISSUE THREAD

**Issue by dittops** [tloen/alpaca-lora#103]
I have tried the following, but it was throwing an error

```
tokenizer = LLaMATokenizer.from_pretrained("/content/drive/MyDrive/alpaca-model/")
model = LLaMAForCausalLM.from_pretrained(
    "/content/drive/MyDrive/alpaca-model/",
    local_files_only=True
)

model = PeftModel.from_pretrained(model, "tloen/alpaca-lora-7b")
```

<img width="786" alt="image" src="https://user-images.githubusercontent.com/12937285/226473984-c885f95c-7ac1-47e6-bc1c-c7dbb4630e19.png">

**Comment by Zachary-Hamel** [comment]
Its LlamaForCausalLM and LlamaTokenizer

**Comment by klaverhenrik** [comment]
I'm having the same problem. I just can't figure out how to load the fine-tuned model weights when running generate.py.

After training, my weights are located in ./lora-alpaca
![Picture1](https://user-images.githubusercontent.com/45521850/227875673-41545848-427d-4e30-8857-8ed70eae1c89.png)

Here is what I have tried:
1) Changing `BASE_MODEL` in generate.py to "./lora-alpaca"
2) Changing `LORA_WEIGHTS` in generate.py to "./lora-alpaca"
3) Both of the above, renaming `adapter_config.json` to `config.json` and renaming `adapter_model.bin` to `pytoch_model.bin` (due to error messages that these files didn't exist)

It is as if the script still attempts to load the model weights from huggingface, instead of from ./lora-alpaca

Has anyone cracked this?

**Comment by LoopControl** [comment]
Don’t rename the adapter files - put it back to original names. Set Base model to the original model it was trained on top of. Only LoRA weights should point to your local folder that contains the adapter files

**Comment by dittops** [comment]
I'm getting this error

```
Traceback (most recent call last):
  File "inference.py", line 26, in <module>
    model = PeftModel.from_pretrained(model, LORA_WEIGHTS, torch_dtype=torch.float16, device_map={'': 0})
  File "/root/bud-llms-backend/server/.env/lib/python3.8/site-packages/peft/peft_model.py", line 135, in from_pretrained
    config = PEFT_TYPE_TO_CONFIG_MAPPING[PeftConfig.from_pretrained(model_id).peft_type].from_pretrained(model_id)
  File "/root/bud-llms-backend/server/.env/lib/python3.8/site-packages/peft/utils/config.py", line 101, in from_pretrained
    raise ValueError(f"Can't find config.json at '{pretrained_model_name_or_path}'")
ValueError: Can't find config.json at './lora-alpaca/'
```

<img width="777" alt="image" src="https://user-images.githubusercontent.com/12937285/230104417-8ef02735-2d13-4c62-9bb4-f7bdab3d9abb.png">

**Comment by LoopControl** [comment]
@mazzzystar Not sure on that but it definitely seems wrong. The .bin file is 26M for a 13B model for me so I'd expect the 7B to be a few MB at least.

**Comment by mazzzystar** [comment]
> > > Don’t rename the adapter files - put it back to original names.
> > > Set Base model to the original model it was trained on top of. Only LoRA_weights should point to your local folder that contains the adapter files
> > 
> > 
> > @LoopControl But why the `adapter_model.bin` file size is small? For 7B model it's only 443 Bytes. <img alt="image" width="280" src="https://user-images.githubusercontent.com/6824141/231362585-5dc62bce-eaf2-4335-bf2e-8ac1094ec92f.png">
> 
> this may help [#293 (comment)](https://github.com/tloen/alpaca-lora/issues/293#issuecomment-1500751776)

@Zombiessss  Thank you very much.
