### ISSUE TITLE
How to improve GPU Memory usage?

### ISSUE THREAD

**Issue by Jiuzhouh** [tloen/alpaca-lora#191]
I am using V100 with 16G memory. When I train the Alpaca-lora using the default setting, I will take 11 hours to train 3 epoch, while only using 9G memory. There are still 7G memory is unused. I wonder are there some methods that improve GPU Memory usage to reduce the training time? I tried to enlarge the batch size, but it has nothing to do with the GPU Memory usage, still 9G. Thanks in advance!

**Comment by Jeffwan** [comment]
@Jiuzhouh What's your batch size setting? Did you change both --batch-size and --micro-batch-size?

**Comment by Jiuzhouh** [comment]
> @Jiuzhouh What's your batch size setting? Did you change both --batch-size and --micro-batch-size?

I tied to use 256 batch size and 8 micro-batch-size, neither of these two could work.

**Comment by AngainorDev** [comment]
Generally speaking, as long as you don't run into OOM, you can enlarge --micro-batch-size (and keep --batch-size roughly to 128)

If micro-batch-size to 8 gives an OOM, you can try with 6.
Always adjust batch-size so that it's divisible by (micro-batch-size * GPU Count) , this will be your auto-computed gradient_accumulation_steps

Doubling the micro batch size (= per device batch size) should roughly half the training time.
Doubling the batch-size just doubles the accumulation steps, little perf gains there. I'd advice to keep it around 128, proven to give ok results.

**Comment by Jiuzhouh** [comment]
> Generally speaking, as long as you don't run into OOM, you can enlarge --micro-batch-size (and keep --batch-size roughly to 128)
> 
> If micro-batch-size to 8 gives an OOM, you can try with 6. Always adjust batch-size so that it's divisible by (micro-batch-size * GPU Count) , this will be your auto-computed gradient_accumulation_steps
> 
> Doubling the micro batch size (= per device batch size) should roughly half the training time. Doubling the batch-size just doubles the accumulation steps, little perf gains there. I'd advice to keep it around 128, proven to give ok results.

Thank you, it's quite clear!

**Comment by shm007g** [comment]
Did you make it faster? 

I am using a V100 32G, micro-batch-size=16, epoch=2, run like 6 hours, cost 11GB. Change seq-len 512 will be 11 hours, cost16GB.
